export enum SocketEventType {
  AUTH_USERNAME = 'AUTH_USERNAME',
  AUTH_USER_ID = 'AUTH_USER_ID',
  MESSAGES = 'MESSAGES',
  SEND_MESSAGE = 'SEND_MESSAGE',
  INITIAL_MESSAGES = 'INITIAL_MESSAGES',
  USER_COUNT = 'USER_COUNT'
}
